swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
     <div onclick=asd class=\"swagger-ui-wrap extraFooter\"><h3>Common Features / Behaviors<\u002fh3> <div class=\"features\"> <ul> <li><strong>* \"sort\" param:<\u002fstrong> supports multi column sorting through the use of commas as delimiters, and a hyphen to denote descending order. <br/> <strong><span>Examples:<\u002fspan><\u002fstrong> <ul> <li><span class=\"example\">name<\u002fspan><span class=\"description\">sort results by name ascending<\u002fspan><\u002fli> <li><span class=\"example\">-name<\u002fspan><span class=\"description\">sort results by name descending<\u002fspan><\u002fli> <li><span class=\"example\">-name,id<\u002fspan><span class=\"description\">sort results by name descending and then by id ascending<\u002fspan><\u002fli> <li><span class=\"example\">id,-dateContentAuthored<\u002fspan><span class=\"description\">sort results by id ascending and then date descending<\u002fspan><\u002fli> <\u002ful> <\u002fli> <li><strong>Date formats:<\u002fstrong> Date input format is expected to be based on <a href=\"http://www.ietf.org/rfc/rfc3339.txt\">RFC 3339<\u002fa>. <br/> <span><strong>Example:<\u002fstrong><\u002fspan> <ul><li>2013-11-18T18:43:01Z<\u002fli><\u002ful> <\u002fli> <\u002ful> <\u002fdiv> <\u002fdiv>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <h1>asd123</h1>

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
